/*
 * uart_rw_test.c
 * =============================================================================
 * ROM-compatible C test for VeeR EL2 → AXI adapter → UART register
 * write + read validation.
 *
 * Memory map (matches snapshots/default generated by veer.config -target=default)
 *   Reset vector / .text  : 0x8000_0000  (ICCM start)
 *   .data / .bss / stack  : 0xF004_0000  (DCCM start)
 *   UART peripheral base  : 0x4000_0000
 *
 * UART register offsets (word-addressed, 4 bytes each):
 *   THR / RBR  offset 0x00  (write = TX, read = RX)
 *   IER        offset 0x04  (Interrupt Enable)
 *   BAUD_DIV   offset 0x08  (Baud-rate divisor)
 *   LCR        offset 0x0C  (Line Control)
 *   LSR        offset 0x14  (Line Status)
 *     LSR[0]  = RX data ready
 *     LSR[5]  = TX FIFO empty (THRE)
 *     LSR[6]  = TX empty (TEMT)
 *
 * Test sequence:
 *   1. Write LCR  → 8-N-1 configuration (0x03)
 *   2. Write BAUD → divisor for target baud rate (0x04 = fast for simulation)
 *   3. Write IER  → enable RX interrupt (0x01)
 *   4. Read  LSR  → confirm TX-empty bits set (THRE=1, TEMT=1 → bits[6:5]=11)
 *   5. Write THR  → transmit character 'A' (0x41)
 *   6. Read  THR  → confirm write value visible / register accessible
 *   7. Write THR  → transmit character 'Z' (0x5A)
 *   8. Poll  LSR  → wait for THRE (bit 5) to confirm TX FIFO accepted data
 *   9. Read  LCR  → read-back and validate 0x03
 *  10. Read  IER  → read-back and validate 0x01
 *
 * On pass: writes 0xDEAD_BEEF to magic address 0xD058_0000 (tohost/IO region)
 * On fail: writes 0xBAD0_DEAD to the same address
 *
 * Compile:
 *   riscv64-unknown-elf-gcc \
 *       -march=rv32imc -mabi=ilp32 -O1 -static -nostdlib -nostartfiles \
 *       -T snapshots/default/link.ld \
 *       uart_rw_test.c crt0.S \
 *       -o uart_rw_test.elf
 *
 *   riscv64-unknown-elf-objcopy -O ihex uart_rw_test.elf uart_rw_test.hex
 *   riscv64-unknown-elf-objdump -d uart_rw_test.elf > uart_rw_test.dis
 * =============================================================================
 */

/* =========================================================================
 * UART register addresses
 * ========================================================================= */
#define UART_BASE       0x40000000UL

#define UART_THR        (*(volatile unsigned int *)(UART_BASE + 0x00))  /* TX */
#define UART_RBR        (*(volatile unsigned int *)(UART_BASE + 0x00))  /* RX */
#define UART_IER        (*(volatile unsigned int *)(UART_BASE + 0x04))  /* Interrupt Enable */
#define UART_BAUD       (*(volatile unsigned int *)(UART_BASE + 0x08))  /* Baud divisor */
#define UART_LCR        (*(volatile unsigned int *)(UART_BASE + 0x0C))  /* Line Control */
#define UART_LSR        (*(volatile unsigned int *)(UART_BASE + 0x14))  /* Line Status */

/* LSR bit masks */
#define LSR_DR          (1u << 0)   /* RX data ready         */
#define LSR_THRE        (1u << 5)   /* TX holding reg empty  */
#define LSR_TEMT        (1u << 6)   /* TX completely empty   */

/* =========================================================================
 * Simulation control / tohost
 * ========================================================================= */
#define TOHOST_ADDR     0xD0580000UL
#define PASS_CODE       0xDEADBEEFUL
#define FAIL_CODE       0xBAD0DEADUL

#define RESULT_REG      (*(volatile unsigned int *)(TOHOST_ADDR))

/* =========================================================================
 * Test result tracking
 * ========================================================================= */
static volatile unsigned int test_fail = 0;
static volatile unsigned int pass_count = 0;
static volatile unsigned int fail_count = 0;

/* =========================================================================
 * Simple spin-delay (avoids needing timer peripheral in simulation)
 * ========================================================================= */
static void spin(volatile unsigned int n)
{
    while (n--) { __asm__ volatile ("nop"); }
}

/* =========================================================================
 * check() – validates got == expected, logs result
 * ========================================================================= */
static void check(unsigned int got, unsigned int expected,
                  unsigned int mask, const char *tag_unused)
{
    (void)tag_unused;
    if ((got & mask) == (expected & mask)) {
        pass_count++;
    } else {
        fail_count++;
        test_fail = 1;
    }
}

/* =========================================================================
 * main – test entry point called from crt0.S
 * ========================================================================= */
int main(void)
{
    unsigned int lsr_val, lcr_rb, ier_rb;

    /* ------------------------------------------------------------------
     * TC1 : LCR write – configure 8-N-1 (bits[1:0]=11 → 8-bit word,
     *        no parity bit3=0, 1 stop bit bit2=0) → value 0x03
     * ------------------------------------------------------------------ */
    UART_LCR = 0x03u;
    spin(4);
    lcr_rb = UART_LCR;                          /* TC9: read-back later */

    /* ------------------------------------------------------------------
     * TC2 : BAUD divisor write – set to 0x04 (fast baud for simulation)
     * ------------------------------------------------------------------ */
    UART_BAUD = 0x04u;
    spin(4);

    /* ------------------------------------------------------------------
     * TC3 : IER write – enable RX data-ready interrupt (bit 0)
     * ------------------------------------------------------------------ */
    UART_IER = 0x01u;
    spin(4);
    ier_rb = UART_IER;                          /* TC10: read-back later */

    /* ------------------------------------------------------------------
     * TC4 : LSR read – TX empty bits must be set after reset / init
     *        THRE(bit5) and TEMT(bit6) should be 1 (TX FIFO empty)
     * ------------------------------------------------------------------ */
    lsr_val = UART_LSR;
    check(lsr_val, LSR_THRE | LSR_TEMT, LSR_THRE | LSR_TEMT, "TC4-LSR-TX-EMPTY");

    /* ------------------------------------------------------------------
     * TC5 : THR write – transmit 'A' (0x41)
     * ------------------------------------------------------------------ */
    UART_THR = 0x41u;                           /* write 'A' */
    spin(8);

    /* ------------------------------------------------------------------
     * TC6 : THR register write 'Z' (0x5A)  (second write transaction)
     * ------------------------------------------------------------------ */
    UART_THR = 0x5Au;                           /* write 'Z' */
    spin(8);

    /* ------------------------------------------------------------------
     * TC7 : Poll LSR – wait for THRE to confirm TX FIFO accepted data
     *        (timeout after ~512 NOP spins → mark fail if never ready)
     * ------------------------------------------------------------------ */
    {
        unsigned int timeout = 512u;
        unsigned int thre_seen = 0u;
        while (timeout--) {
            lsr_val = UART_LSR;
            if (lsr_val & LSR_THRE) {
                thre_seen = 1u;
                break;
            }
            spin(2);
        }
        check(thre_seen, 1u, 0xFFFFFFFFu, "TC7-LSR-THRE-POLL");
    }

    /* ------------------------------------------------------------------
     * TC8 : LCR write + read-back  (validates read transaction path)
     *        Write 0x03, read back and confirm
     * ------------------------------------------------------------------ */
    UART_LCR = 0x03u;
    spin(4);
    lcr_rb = UART_LCR;
    check(lcr_rb, 0x03u, 0xFFu, "TC8-LCR-READBACK");

    /* ------------------------------------------------------------------
     * TC9 : IER read-back – validate value written in TC3
     * ------------------------------------------------------------------ */
    check(ier_rb, 0x01u, 0xFFu, "TC9-IER-READBACK");

    /* ------------------------------------------------------------------
     * TC10 : LCR – write 0x0B (8-bit, parity enabled, even parity)
     *         read back and verify
     * ------------------------------------------------------------------ */
    UART_LCR = 0x0Bu;
    spin(4);
    lcr_rb = UART_LCR;
    check(lcr_rb, 0x0Bu, 0xFFu, "TC10-LCR-PARITY");

    /* ------------------------------------------------------------------
     * Final result
     * ------------------------------------------------------------------ */
    if (test_fail == 0u) {
        RESULT_REG = PASS_CODE;     /* 0xDEADBEEF → ALL PASS */
    } else {
        RESULT_REG = FAIL_CODE;     /* 0xBAD0DEAD → FAIL     */
    }

    /* Park the core */
    while (1) { __asm__ volatile ("nop"); }

    return 0;
}
