// =============================================================================
// Module  : veer_soc_top
// File    : RTL_files/veer_soc_top.v
//
// Purpose : Full-system integration model for simulation.
//           Wraps veer_wrapper_uart_integrated and adds:
//             1. IMEM  – 64-bit AXI4 instruction memory slave
//                        Loaded from hex file via $readmemh
//                        Responds to IFU AXI read requests at 0x8000_0000
//             2. Tie-offs for all unused top-level ports:
//                SB (debug system bus), DMA slave, JTAG, scan, etc.
//             3. tohost monitor – watches writes to 0xD058_0000 and
//                prints PASS / FAIL based on the written value
//
// Memory map:
//   0x8000_0000 – 0x8000_FFFF   IMEM  (64 KB, 8192 x 64-bit words)
//   0x4000_0000 – 0x4000_001F   UART  (via interconnect inside DUT)
//   0xD058_0000                 tohost / simulation exit register
//
// Parameters:
//   IMEM_FILE   – path to hex file produced by uart_rw_test build
//   CLK_PERIOD  – system clock half-period in ns (default 5 → 100 MHz)
//
// Usage (compile together with runf.f):
//   vcs -full64 -sverilog -debug_access+all -kdb \
//       +define+RV_BUILD_AXI4 +define+RV_PHYSICAL \
//       -f run/runf.f \
//       RTL_files/veer_soc_top.v \
//       +define+IMEM_FILE=\"uart_rw_test.hex\" \
//       -o simv_soc
//   ./simv_soc +fsdb+delta -l sim_soc.log
// =============================================================================

`timescale 1ns/1ps
`default_nettype none

module veer_soc_top #(
    // Path to the compiled hex file (overridden via +define+IMEM_FILE=...)
    parameter IMEM_FILE   = "uart_rw_test.hex",
    parameter CLK_PERIOD  = 5,      // ns, half-period → 100 MHz
    parameter RST_CYCLES  = 20      // clock cycles to hold reset
)(
    // Expose clock/reset for optional external drive in co-simulation
    input  wire  ext_clk_i,
    input  wire  ext_rst_n_i,
    input  wire  ext_clk_en_i      // 1 = use internal clock gen, 0 = use ext_clk_i
);

    // =========================================================================
    // Parameters matching VeeR EL2 defaults (generated by veer.config)
    // =========================================================================
    localparam IC_ID_WIDTH  = 8;
    localparam DATA_WIDTH   = 32;
    localparam ADDR_WIDTH   = 32;
    localparam LSU_BUS_TAG  = 3;
    localparam IFU_BUS_TAG  = 3;
    localparam SB_BUS_TAG   = 1;
    localparam DMA_BUS_TAG  = 1;
    localparam PIC_TOTAL_INT= 31;

    // IMEM: 64 KB / 8 bytes per word = 8192 locations
    localparam IMEM_DEPTH   = 8192;
    localparam IMEM_BASE    = 32'h8000_0000;

    // tohost address
    localparam TOHOST_ADDR  = 32'hD058_0000;

    // =========================================================================
    // Clock and reset generation
    // =========================================================================
    reg  clk_int = 1'b0;
    always #(CLK_PERIOD) clk_int = ~clk_int;

    wire clk       = ext_clk_en_i ? clk_int : ext_clk_i;
    wire fixed_clk = clk;   // UART baud reference = system clock in simulation

    reg  rst_n_r   = 1'b0;
    integer rst_cnt = 0;
    always @(posedge clk) begin
        if (rst_cnt < RST_CYCLES) begin
            rst_n_r <= 1'b0;
            rst_cnt <= rst_cnt + 1;
        end else begin
            rst_n_r <= 1'b1;
        end
    end

    wire rst_l     = ext_clk_en_i ? rst_n_r : ext_rst_n_i;
    wire dbg_rst_l = rst_l;

    // =========================================================================
    // IFU AXI wires (DUT output → IMEM input)
    // =========================================================================
    wire                    ifu_axi_arvalid;
    wire                    ifu_axi_arready;
    wire [IFU_BUS_TAG-1:0]  ifu_axi_arid;
    wire [31:0]             ifu_axi_araddr;
    wire [3:0]              ifu_axi_arregion;
    wire [7:0]              ifu_axi_arlen;
    wire [2:0]              ifu_axi_arsize;
    wire [1:0]              ifu_axi_arburst;
    wire                    ifu_axi_arlock;
    wire [3:0]              ifu_axi_arcache;
    wire [2:0]              ifu_axi_arprot;
    wire [3:0]              ifu_axi_arqos;

    wire                    ifu_axi_rvalid;
    wire                    ifu_axi_rready;
    wire [IFU_BUS_TAG-1:0]  ifu_axi_rid;
    wire [63:0]             ifu_axi_rdata;
    wire [1:0]              ifu_axi_rresp;
    wire                    ifu_axi_rlast;

    // IFU write channel – IFU never writes; tie off inputs to DUT
    wire                    ifu_axi_awvalid;
    wire                    ifu_axi_awready = 1'b0;
    wire [IFU_BUS_TAG-1:0]  ifu_axi_awid;
    wire [31:0]             ifu_axi_awaddr;
    wire [3:0]              ifu_axi_awregion;
    wire [7:0]              ifu_axi_awlen;
    wire [2:0]              ifu_axi_awsize;
    wire [1:0]              ifu_axi_awburst;
    wire                    ifu_axi_awlock;
    wire [3:0]              ifu_axi_awcache;
    wire [2:0]              ifu_axi_awprot;
    wire [3:0]              ifu_axi_awqos;
    wire                    ifu_axi_wvalid;
    wire                    ifu_axi_wready  = 1'b0;
    wire [63:0]             ifu_axi_wdata;
    wire [7:0]              ifu_axi_wstrb;
    wire                    ifu_axi_wlast;
    wire                    ifu_axi_bvalid  = 1'b0;
    wire                    ifu_axi_bready;
    wire [1:0]              ifu_axi_bresp   = 2'b00;
    wire [IFU_BUS_TAG-1:0]  ifu_axi_bid     = {IFU_BUS_TAG{1'b0}};

    // =========================================================================
    // SB (debug system bus) AXI – tie off (not used in this integration)
    // =========================================================================
    wire                    sb_axi_awvalid;
    wire                    sb_axi_awready  = 1'b0;
    wire [SB_BUS_TAG-1:0]   sb_axi_awid;
    wire [31:0]             sb_axi_awaddr;
    wire [3:0]              sb_axi_awregion;
    wire [7:0]              sb_axi_awlen;
    wire [2:0]              sb_axi_awsize;
    wire [1:0]              sb_axi_awburst;
    wire                    sb_axi_awlock;
    wire [3:0]              sb_axi_awcache;
    wire [2:0]              sb_axi_awprot;
    wire [3:0]              sb_axi_awqos;
    wire                    sb_axi_wvalid;
    wire                    sb_axi_wready   = 1'b0;
    wire [63:0]             sb_axi_wdata;
    wire [7:0]              sb_axi_wstrb;
    wire                    sb_axi_wlast;
    wire                    sb_axi_bvalid   = 1'b0;
    wire                    sb_axi_bready;
    wire [1:0]              sb_axi_bresp    = 2'b00;
    wire [SB_BUS_TAG-1:0]   sb_axi_bid      = {SB_BUS_TAG{1'b0}};
    wire                    sb_axi_arvalid;
    wire                    sb_axi_arready  = 1'b0;
    wire [SB_BUS_TAG-1:0]   sb_axi_arid;
    wire [31:0]             sb_axi_araddr;
    wire [3:0]              sb_axi_arregion;
    wire [7:0]              sb_axi_arlen;
    wire [2:0]              sb_axi_arsize;
    wire [1:0]              sb_axi_arburst;
    wire                    sb_axi_arlock;
    wire [3:0]              sb_axi_arcache;
    wire [2:0]              sb_axi_arprot;
    wire [3:0]              sb_axi_arqos;
    wire                    sb_axi_rvalid   = 1'b0;
    wire                    sb_axi_rready;
    wire [SB_BUS_TAG-1:0]   sb_axi_rid      = {SB_BUS_TAG{1'b0}};
    wire [63:0]             sb_axi_rdata    = 64'h0;
    wire [1:0]              sb_axi_rresp    = 2'b00;
    wire                    sb_axi_rlast    = 1'b0;

    // =========================================================================
    // DMA AXI slave – tie off (no external DMA master in this testbench)
    // =========================================================================
    wire                    dma_axi_awvalid = 1'b0;
    wire                    dma_axi_awready;
    wire [DMA_BUS_TAG-1:0]  dma_axi_awid    = {DMA_BUS_TAG{1'b0}};
    wire [31:0]             dma_axi_awaddr  = 32'h0;
    wire [2:0]              dma_axi_awsize  = 3'b0;
    wire [2:0]              dma_axi_awprot  = 3'b0;
    wire [7:0]              dma_axi_awlen   = 8'h0;
    wire [1:0]              dma_axi_awburst = 2'b01;
    wire                    dma_axi_wvalid  = 1'b0;
    wire                    dma_axi_wready;
    wire [63:0]             dma_axi_wdata   = 64'h0;
    wire [7:0]              dma_axi_wstrb   = 8'h0;
    wire                    dma_axi_wlast   = 1'b0;
    wire                    dma_axi_bvalid;
    wire                    dma_axi_bready  = 1'b1;
    wire [1:0]              dma_axi_bresp;
    wire [DMA_BUS_TAG-1:0]  dma_axi_bid;
    wire                    dma_axi_arvalid = 1'b0;
    wire                    dma_axi_arready;
    wire [DMA_BUS_TAG-1:0]  dma_axi_arid    = {DMA_BUS_TAG{1'b0}};
    wire [31:0]             dma_axi_araddr  = 32'h0;
    wire [2:0]              dma_axi_arsize  = 3'b0;
    wire [2:0]              dma_axi_arprot  = 3'b0;
    wire [7:0]              dma_axi_arlen   = 8'h0;
    wire [1:0]              dma_axi_arburst = 2'b01;
    wire                    dma_axi_rvalid;
    wire                    dma_axi_rready  = 1'b1;
    wire [DMA_BUS_TAG-1:0]  dma_axi_rid;
    wire [63:0]             dma_axi_rdata;
    wire [1:0]              dma_axi_rresp;
    wire                    dma_axi_rlast;

    // =========================================================================
    // s01 secondary AXI slave – tie off (no secondary master)
    // =========================================================================
    wire [IC_ID_WIDTH-1:0]  s01_axi_awid    = {IC_ID_WIDTH{1'b0}};
    wire [ADDR_WIDTH-1:0]   s01_axi_awaddr  = 32'h0;
    wire [7:0]              s01_axi_awlen   = 8'h0;
    wire [2:0]              s01_axi_awsize  = 3'h0;
    wire [1:0]              s01_axi_awburst = 2'b01;
    wire                    s01_axi_awlock  = 1'b0;
    wire [3:0]              s01_axi_awcache = 4'h0;
    wire [2:0]              s01_axi_awprot  = 3'h0;
    wire [3:0]              s01_axi_awqos   = 4'h0;
    wire                    s01_axi_awvalid = 1'b0;
    wire                    s01_axi_awready;
    wire [DATA_WIDTH-1:0]   s01_axi_wdata   = 32'h0;
    wire [DATA_WIDTH/8-1:0] s01_axi_wstrb   = 4'h0;
    wire                    s01_axi_wlast   = 1'b0;
    wire                    s01_axi_wvalid  = 1'b0;
    wire                    s01_axi_wready;
    wire [IC_ID_WIDTH-1:0]  s01_axi_bid;
    wire [1:0]              s01_axi_bresp;
    wire                    s01_axi_bvalid;
    wire                    s01_axi_bready  = 1'b1;
    wire [IC_ID_WIDTH-1:0]  s01_axi_arid    = {IC_ID_WIDTH{1'b0}};
    wire [ADDR_WIDTH-1:0]   s01_axi_araddr  = 32'h0;
    wire [7:0]              s01_axi_arlen   = 8'h0;
    wire [2:0]              s01_axi_arsize  = 3'h0;
    wire [1:0]              s01_axi_arburst = 2'b01;
    wire                    s01_axi_arlock  = 1'b0;
    wire [3:0]              s01_axi_arcache = 4'h0;
    wire [2:0]              s01_axi_arprot  = 3'h0;
    wire [3:0]              s01_axi_arqos   = 4'h0;
    wire                    s01_axi_arvalid = 1'b0;
    wire                    s01_axi_arready;
    wire [IC_ID_WIDTH-1:0]  s01_axi_rid;
    wire [DATA_WIDTH-1:0]   s01_axi_rdata;
    wire [1:0]              s01_axi_rresp;
    wire                    s01_axi_rlast;
    wire                    s01_axi_rvalid;
    wire                    s01_axi_rready  = 1'b1;

    // =========================================================================
    // Miscellaneous DUT input signals – tie off
    // =========================================================================
    wire                    uart_rx_i       = 1'b1; // idle line
    wire                    uart_tx_o;
    wire                    uart_read_irq_o;

    wire [PIC_TOTAL_INT:1]  extintsrc_req   = {PIC_TOTAL_INT{1'b0}};
    wire                    nmi_int         = 1'b0;
    wire                    timer_int       = 1'b0;
    wire                    soft_int        = 1'b0;

    wire [31:1]             rst_vec         = 31'h4000_0000; // reset vector 0x80000000
    wire [31:1]             nmi_vec         = 31'h1ee1_0000;
    wire [31:1]             jtag_id         = 31'h0000_0001;
    wire [31:4]             core_id         = 28'h0;

    wire                    jtag_tck        = 1'b0;
    wire                    jtag_tms        = 1'b0;
    wire                    jtag_tdi        = 1'b0;
    wire                    jtag_trst_n     = 1'b1;
    wire                    jtag_tdo;
    wire                    jtag_tdoEn;

    wire                    lsu_bus_clk_en  = 1'b1;
    wire                    ifu_bus_clk_en  = 1'b1;
    wire                    dbg_bus_clk_en  = 1'b1;
    wire                    dma_bus_clk_en  = 1'b1;
    wire                    scan_mode       = 1'b0;
    wire                    mbist_mode      = 1'b0;

    wire                    dmi_core_enable   = 1'b0;
    wire                    dmi_uncore_enable = 1'b0;
    wire                    dmi_uncore_en;
    wire                    dmi_uncore_wr_en;
    wire [6:0]              dmi_uncore_addr;
    wire [31:0]             dmi_uncore_wdata;
    wire [31:0]             dmi_uncore_rdata  = 32'h0;
    wire                    dmi_active;

    wire                    mpc_debug_halt_req = 1'b0;
    wire                    mpc_debug_run_req  = 1'b0;
    wire                    mpc_reset_run_req  = 1'b1;
    wire                    mpc_debug_halt_ack;
    wire                    mpc_debug_run_ack;
    wire                    debug_brkpt_status;
    wire                    i_cpu_halt_req     = 1'b0;
    wire                    o_cpu_halt_ack;
    wire                    o_cpu_halt_status;
    wire                    o_debug_mode_status;
    wire                    i_cpu_run_req      = 1'b0;
    wire                    o_cpu_run_ack;

    // =========================================================================
    // DUT: veer_wrapper_uart_integrated
    // =========================================================================
    veer_wrapper_uart_integrated #(
        .IC_ID_WIDTH    (IC_ID_WIDTH),
        .DATA_WIDTH     (DATA_WIDTH),
        .ADDR_WIDTH     (ADDR_WIDTH),
        .LSU_BUS_TAG    (LSU_BUS_TAG),
        .IFU_BUS_TAG    (IFU_BUS_TAG),
        .SB_BUS_TAG     (SB_BUS_TAG),
        .DMA_BUS_TAG    (DMA_BUS_TAG),
        .PIC_TOTAL_INT  (PIC_TOTAL_INT),
        .UART_BASE_ADDR (32'h4000_0000)
    ) dut (
        .clk                        (clk),
        .rst_l                      (rst_l),
        .dbg_rst_l                  (dbg_rst_l),
        .fixed_clk                  (fixed_clk),
        .rst_vec                    (rst_vec),
        .nmi_vec                    (nmi_vec),
        .jtag_id                    (jtag_id),
        .core_id                    (core_id),
        .nmi_int                    (nmi_int),
        .timer_int                  (timer_int),
        .soft_int                   (soft_int),
        .extintsrc_req              (extintsrc_req),
        .uart_read_irq_o            (uart_read_irq_o),
        .uart_tx_o                  (uart_tx_o),
        .uart_rx_i                  (uart_rx_i),
        // IFU AXI
        .ifu_axi_arvalid            (ifu_axi_arvalid),
        .ifu_axi_arready            (ifu_axi_arready),
        .ifu_axi_arid               (ifu_axi_arid),
        .ifu_axi_araddr             (ifu_axi_araddr),
        .ifu_axi_arregion           (ifu_axi_arregion),
        .ifu_axi_arlen              (ifu_axi_arlen),
        .ifu_axi_arsize             (ifu_axi_arsize),
        .ifu_axi_arburst            (ifu_axi_arburst),
        .ifu_axi_arlock             (ifu_axi_arlock),
        .ifu_axi_arcache            (ifu_axi_arcache),
        .ifu_axi_arprot             (ifu_axi_arprot),
        .ifu_axi_arqos              (ifu_axi_arqos),
        .ifu_axi_rvalid             (ifu_axi_rvalid),
        .ifu_axi_rready             (ifu_axi_rready),
        .ifu_axi_rid                (ifu_axi_rid),
        .ifu_axi_rdata              (ifu_axi_rdata),
        .ifu_axi_rresp              (ifu_axi_rresp),
        .ifu_axi_rlast              (ifu_axi_rlast),
        .ifu_axi_awvalid            (ifu_axi_awvalid),
        .ifu_axi_awready            (ifu_axi_awready),
        .ifu_axi_awid               (ifu_axi_awid),
        .ifu_axi_awaddr             (ifu_axi_awaddr),
        .ifu_axi_awregion           (ifu_axi_awregion),
        .ifu_axi_awlen              (ifu_axi_awlen),
        .ifu_axi_awsize             (ifu_axi_awsize),
        .ifu_axi_awburst            (ifu_axi_awburst),
        .ifu_axi_awlock             (ifu_axi_awlock),
        .ifu_axi_awcache            (ifu_axi_awcache),
        .ifu_axi_awprot             (ifu_axi_awprot),
        .ifu_axi_awqos              (ifu_axi_awqos),
        .ifu_axi_wvalid             (ifu_axi_wvalid),
        .ifu_axi_wready             (ifu_axi_wready),
        .ifu_axi_wdata              (ifu_axi_wdata),
        .ifu_axi_wstrb              (ifu_axi_wstrb),
        .ifu_axi_wlast              (ifu_axi_wlast),
        .ifu_axi_bvalid             (ifu_axi_bvalid),
        .ifu_axi_bready             (ifu_axi_bready),
        .ifu_axi_bresp              (ifu_axi_bresp),
        .ifu_axi_bid                (ifu_axi_bid),
        // SB AXI
        .sb_axi_awvalid             (sb_axi_awvalid),
        .sb_axi_awready             (sb_axi_awready),
        .sb_axi_awid                (sb_axi_awid),
        .sb_axi_awaddr              (sb_axi_awaddr),
        .sb_axi_awregion            (sb_axi_awregion),
        .sb_axi_awlen               (sb_axi_awlen),
        .sb_axi_awsize              (sb_axi_awsize),
        .sb_axi_awburst             (sb_axi_awburst),
        .sb_axi_awlock              (sb_axi_awlock),
        .sb_axi_awcache             (sb_axi_awcache),
        .sb_axi_awprot              (sb_axi_awprot),
        .sb_axi_awqos               (sb_axi_awqos),
        .sb_axi_wvalid              (sb_axi_wvalid),
        .sb_axi_wready              (sb_axi_wready),
        .sb_axi_wdata               (sb_axi_wdata),
        .sb_axi_wstrb               (sb_axi_wstrb),
        .sb_axi_wlast               (sb_axi_wlast),
        .sb_axi_bvalid              (sb_axi_bvalid),
        .sb_axi_bready              (sb_axi_bready),
        .sb_axi_bresp               (sb_axi_bresp),
        .sb_axi_bid                 (sb_axi_bid),
        .sb_axi_arvalid             (sb_axi_arvalid),
        .sb_axi_arready             (sb_axi_arready),
        .sb_axi_arid                (sb_axi_arid),
        .sb_axi_araddr              (sb_axi_araddr),
        .sb_axi_arregion            (sb_axi_arregion),
        .sb_axi_arlen               (sb_axi_arlen),
        .sb_axi_arsize              (sb_axi_arsize),
        .sb_axi_arburst             (sb_axi_arburst),
        .sb_axi_arlock              (sb_axi_arlock),
        .sb_axi_arcache             (sb_axi_arcache),
        .sb_axi_arprot              (sb_axi_arprot),
        .sb_axi_arqos               (sb_axi_arqos),
        .sb_axi_rvalid              (sb_axi_rvalid),
        .sb_axi_rready              (sb_axi_rready),
        .sb_axi_rid                 (sb_axi_rid),
        .sb_axi_rdata               (sb_axi_rdata),
        .sb_axi_rresp               (sb_axi_rresp),
        .sb_axi_rlast               (sb_axi_rlast),
        // DMA AXI
        .dma_axi_awvalid            (dma_axi_awvalid),
        .dma_axi_awready            (dma_axi_awready),
        .dma_axi_awid               (dma_axi_awid),
        .dma_axi_awaddr             (dma_axi_awaddr),
        .dma_axi_awsize             (dma_axi_awsize),
        .dma_axi_awprot             (dma_axi_awprot),
        .dma_axi_awlen              (dma_axi_awlen),
        .dma_axi_awburst            (dma_axi_awburst),
        .dma_axi_wvalid             (dma_axi_wvalid),
        .dma_axi_wready             (dma_axi_wready),
        .dma_axi_wdata              (dma_axi_wdata),
        .dma_axi_wstrb              (dma_axi_wstrb),
        .dma_axi_wlast              (dma_axi_wlast),
        .dma_axi_bvalid             (dma_axi_bvalid),
        .dma_axi_bready             (dma_axi_bready),
        .dma_axi_bresp              (dma_axi_bresp),
        .dma_axi_bid                (dma_axi_bid),
        .dma_axi_arvalid            (dma_axi_arvalid),
        .dma_axi_arready            (dma_axi_arready),
        .dma_axi_arid               (dma_axi_arid),
        .dma_axi_araddr             (dma_axi_araddr),
        .dma_axi_arsize             (dma_axi_arsize),
        .dma_axi_arprot             (dma_axi_arprot),
        .dma_axi_arlen              (dma_axi_arlen),
        .dma_axi_arburst            (dma_axi_arburst),
        .dma_axi_rvalid             (dma_axi_rvalid),
        .dma_axi_rready             (dma_axi_rready),
        .dma_axi_rid                (dma_axi_rid),
        .dma_axi_rdata              (dma_axi_rdata),
        .dma_axi_rresp              (dma_axi_rresp),
        .dma_axi_rlast              (dma_axi_rlast),
        // s01 secondary master
        .s01_axi_awid               (s01_axi_awid),
        .s01_axi_awaddr             (s01_axi_awaddr),
        .s01_axi_awlen              (s01_axi_awlen),
        .s01_axi_awsize             (s01_axi_awsize),
        .s01_axi_awburst            (s01_axi_awburst),
        .s01_axi_awlock             (s01_axi_awlock),
        .s01_axi_awcache            (s01_axi_awcache),
        .s01_axi_awprot             (s01_axi_awprot),
        .s01_axi_awqos              (s01_axi_awqos),
        .s01_axi_awvalid            (s01_axi_awvalid),
        .s01_axi_awready            (s01_axi_awready),
        .s01_axi_wdata              (s01_axi_wdata),
        .s01_axi_wstrb              (s01_axi_wstrb),
        .s01_axi_wlast              (s01_axi_wlast),
        .s01_axi_wvalid             (s01_axi_wvalid),
        .s01_axi_wready             (s01_axi_wready),
        .s01_axi_bid                (s01_axi_bid),
        .s01_axi_bresp              (s01_axi_bresp),
        .s01_axi_bvalid             (s01_axi_bvalid),
        .s01_axi_bready             (s01_axi_bready),
        .s01_axi_arid               (s01_axi_arid),
        .s01_axi_araddr             (s01_axi_araddr),
        .s01_axi_arlen              (s01_axi_arlen),
        .s01_axi_arsize             (s01_axi_arsize),
        .s01_axi_arburst            (s01_axi_arburst),
        .s01_axi_arlock             (s01_axi_arlock),
        .s01_axi_arcache            (s01_axi_arcache),
        .s01_axi_arprot             (s01_axi_arprot),
        .s01_axi_arqos              (s01_axi_arqos),
        .s01_axi_arvalid            (s01_axi_arvalid),
        .s01_axi_arready            (s01_axi_arready),
        .s01_axi_rid                (s01_axi_rid),
        .s01_axi_rdata              (s01_axi_rdata),
        .s01_axi_rresp              (s01_axi_rresp),
        .s01_axi_rlast              (s01_axi_rlast),
        .s01_axi_rvalid             (s01_axi_rvalid),
        .s01_axi_rready             (s01_axi_rready),
        // Trace (ignore outputs)
        .trace_rv_i_insn_ip         (),
        .trace_rv_i_address_ip      (),
        .trace_rv_i_valid_ip        (),
        .trace_rv_i_exception_ip    (),
        .trace_rv_i_ecause_ip       (),
        .trace_rv_i_interrupt_ip    (),
        .trace_rv_i_tval_ip         (),
        // ECC (ignore)
        .iccm_ecc_single_error      (),
        .iccm_ecc_double_error      (),
        .dccm_ecc_single_error      (),
        .dccm_ecc_double_error      (),
        .dccm_write_readback_error  (),
        // Perf counters (ignore)
        .dec_tlu_perfcnt0           (),
        .dec_tlu_perfcnt1           (),
        .dec_tlu_perfcnt2           (),
        .dec_tlu_perfcnt3           (),
        // JTAG
        .jtag_tck                   (jtag_tck),
        .jtag_tms                   (jtag_tms),
        .jtag_tdi                   (jtag_tdi),
        .jtag_trst_n                (jtag_trst_n),
        .jtag_tdo                   (jtag_tdo),
        .jtag_tdoEn                 (jtag_tdoEn),
        // MPC
        .mpc_debug_halt_req         (mpc_debug_halt_req),
        .mpc_debug_run_req          (mpc_debug_run_req),
        .mpc_reset_run_req          (mpc_reset_run_req),
        .mpc_debug_halt_ack         (mpc_debug_halt_ack),
        .mpc_debug_run_ack          (mpc_debug_run_ack),
        .debug_brkpt_status         (debug_brkpt_status),
        .i_cpu_halt_req             (i_cpu_halt_req),
        .o_cpu_halt_ack             (o_cpu_halt_ack),
        .o_cpu_halt_status          (o_cpu_halt_status),
        .o_debug_mode_status        (o_debug_mode_status),
        .i_cpu_run_req              (i_cpu_run_req),
        .o_cpu_run_ack              (o_cpu_run_ack),
        // Clock enables
        .lsu_bus_clk_en             (lsu_bus_clk_en),
        .ifu_bus_clk_en             (ifu_bus_clk_en),
        .dbg_bus_clk_en             (dbg_bus_clk_en),
        .dma_bus_clk_en             (dma_bus_clk_en),
        // Misc
        .scan_mode                  (scan_mode),
        .mbist_mode                 (mbist_mode),
        // DMI
        .dmi_core_enable            (dmi_core_enable),
        .dmi_uncore_enable          (dmi_uncore_enable),
        .dmi_uncore_en              (dmi_uncore_en),
        .dmi_uncore_wr_en           (dmi_uncore_wr_en),
        .dmi_uncore_addr            (dmi_uncore_addr),
        .dmi_uncore_wdata           (dmi_uncore_wdata),
        .dmi_uncore_rdata           (dmi_uncore_rdata),
        .dmi_active                 (dmi_active)
    );

    // =========================================================================
    // IMEM – AXI4 instruction memory slave (64-bit data, single-beat)
    // Base address: 0x8000_0000  Size: 64 KB = 8192 x 64-bit words
    //
    // Protocol:
    //   - Accepts AR channel when address is in IMEM range
    //   - Returns rdata one cycle after AR handshake (zero-latency RAM model)
    //   - Supports arlen > 0 (burst) by incrementing address each beat
    //   - arsize=3 (8 bytes) expected from IFU – returns full 64-bit word
    // =========================================================================
    reg [63:0] imem [0:IMEM_DEPTH-1];

    // Load hex file at time 0
    initial begin
        integer i;
        for (i = 0; i < IMEM_DEPTH; i = i + 1)
            imem[i] = 64'h0000_0000_0000_0013; // default: NOP (ADDI x0,x0,0)
        $readmemh(IMEM_FILE, imem);
        $display("[IMEM] Loaded '%s' into instruction memory (%0d x 64-bit words)",
                 IMEM_FILE, IMEM_DEPTH);
    end

    // IMEM AXI state machine
    reg  [1:0]             imem_state;
    localparam IMEM_IDLE   = 2'd0;
    localparam IMEM_RDATA  = 2'd1;

    reg  [IFU_BUS_TAG-1:0] imem_rid_r;
    reg  [31:0]            imem_araddr_r;
    reg  [7:0]             imem_arlen_r;
    reg  [7:0]             imem_beat_r;    // current beat count
    reg                    imem_arready_r;
    reg                    imem_rvalid_r;
    reg  [63:0]            imem_rdata_r;
    reg                    imem_rlast_r;

    assign ifu_axi_arready = imem_arready_r;
    assign ifu_axi_rvalid  = imem_rvalid_r;
    assign ifu_axi_rid     = imem_rid_r;
    assign ifu_axi_rdata   = imem_rdata_r;
    assign ifu_axi_rresp   = 2'b00;
    assign ifu_axi_rlast   = imem_rlast_r;

    always @(posedge clk or negedge rst_l) begin
        if (!rst_l) begin
            imem_state    <= IMEM_IDLE;
            imem_arready_r<= 1'b1;
            imem_rvalid_r <= 1'b0;
            imem_rlast_r  <= 1'b0;
            imem_beat_r   <= 8'h0;
            imem_rdata_r  <= 64'h0;
            imem_rid_r    <= {IFU_BUS_TAG{1'b0}};
            imem_araddr_r <= 32'h0;
            imem_arlen_r  <= 8'h0;
        end else begin
            case (imem_state)
                IMEM_IDLE: begin
                    imem_rvalid_r <= 1'b0;
                    imem_arready_r<= 1'b1;
                    if (ifu_axi_arvalid && imem_arready_r) begin
                        imem_arready_r <= 1'b0;
                        imem_rid_r     <= ifu_axi_arid;
                        imem_araddr_r  <= ifu_axi_araddr;
                        imem_arlen_r   <= ifu_axi_arlen;
                        imem_beat_r    <= 8'h0;
                        imem_state     <= IMEM_RDATA;
                        // Present first beat immediately next cycle
                        imem_rvalid_r  <= 1'b1;
                        imem_rdata_r   <= imem[(ifu_axi_araddr - IMEM_BASE) >> 3];
                        imem_rlast_r   <= (ifu_axi_arlen == 8'h0);
                    end
                end
                IMEM_RDATA: begin
                    if (imem_rvalid_r && ifu_axi_rready) begin
                        if (imem_rlast_r) begin
                            // Last beat accepted
                            imem_rvalid_r  <= 1'b0;
                            imem_rlast_r   <= 1'b0;
                            imem_arready_r <= 1'b1;
                            imem_state     <= IMEM_IDLE;
                        end else begin
                            // Advance to next beat
                            imem_beat_r   <= imem_beat_r + 8'h1;
                            imem_araddr_r <= imem_araddr_r + 32'h8;
                            imem_rdata_r  <= imem[(imem_araddr_r + 32'h8 - IMEM_BASE) >> 3];
                            imem_rlast_r  <= (imem_beat_r + 8'h1 == imem_arlen_r);
                        end
                    end
                end
                default: imem_state <= IMEM_IDLE;
            endcase
        end
    end

    // =========================================================================
    // tohost monitor
    // Watches the LSU AXI write channel inside the DUT for writes to TOHOST.
    // We tap the internal lsu_axi_*_w wires via hierarchical reference.
    // =========================================================================
    wire        lsu_aw_hs = dut.u_dwidth_conv.m_axi_awvalid &&
                            dut.u_dwidth_conv.m_axi_awready;
    wire        lsu_w_hs  = dut.u_dwidth_conv.m_axi_wvalid  &&
                            dut.u_dwidth_conv.m_axi_wready;

    reg  [31:0] lsu_awaddr_lat;
    reg         lsu_aw_pend;

    always @(posedge clk or negedge rst_l) begin
        if (!rst_l) begin
            lsu_awaddr_lat <= 32'h0;
            lsu_aw_pend    <= 1'b0;
        end else begin
            if (lsu_aw_hs) begin
                lsu_awaddr_lat <= dut.u_dwidth_conv.m_axi_awaddr;
                lsu_aw_pend    <= 1'b1;
            end
            if (lsu_w_hs && lsu_aw_pend) begin
                lsu_aw_pend <= 1'b0;
                if (lsu_awaddr_lat == TOHOST_ADDR) begin
                    $display("\n[TOHOST @ %0t ns] write = 0x%08h", $time,
                             dut.u_dwidth_conv.m_axi_wdata[31:0]);
                    if (dut.u_dwidth_conv.m_axi_wdata[31:0] == 32'hDEAD_BEEF) begin
                        $display(">>> [PASS] uart_rw_test: ALL TESTS PASSED <<<\n");
                    end else begin
                        $display(">>> [FAIL] uart_rw_test: FAIL CODE = 0x%08h <<<\n",
                                 dut.u_dwidth_conv.m_axi_wdata[31:0]);
                    end
                    $finish;
                end
            end
        end
    end

    // =========================================================================
    // UART TX monitor – print each transmitted byte
    // =========================================================================
    reg uart_tx_prev = 1'b1;
    always @(posedge clk) begin
        uart_tx_prev <= uart_tx_o;
        if (uart_tx_prev && !uart_tx_o)
            $display("[UART-TX @ %0t ns] start-bit detected on uart_tx_o", $time);
    end

    // =========================================================================
    // Simulation timeout watchdog (50 ms @ 100 MHz = 5,000,000 cycles)
    // =========================================================================
    initial begin
        #(5_000_000 * CLK_PERIOD * 2);
        $display("[TIMEOUT] Simulation exceeded limit – no tohost write detected");
        $finish;
    end

    // =========================================================================
    // Waveform dump
    // =========================================================================
    initial begin
        $fsdbDumpfile("veer_soc_top.fsdb");
        $fsdbDumpvars(0, veer_soc_top);
        $dumpfile("veer_soc_top.vcd");
        $dumpvars(0, veer_soc_top);
        $display("[SIM] Starting veer_soc_top full-system simulation");
        $display("[SIM] Clock period = %0d ns, Reset cycles = %0d", CLK_PERIOD*2, RST_CYCLES);
    end

endmodule

`default_nettype wire
